import { ImageResponse } from "next/og";
import type { NextRequest } from "next/server";

import { SITE_NAME } from "@/shared/lib/site";

export const contentType = "image/png";

const SIZE = { width: 1200, height: 630 };

// OG images are generated by this route (not an opengraph-image file) because
// the docs route uses an optional catch-all `[[...slug]]` segment, which must
// be the last segment and cannot colocate metadata image files. Pages point
// their openGraph.images here with ?title= & ?description=.
export function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const title = searchParams.get("title")?.slice(0, 120) || SITE_NAME;
  const description = searchParams.get("description")?.slice(0, 200) || "";

  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: "80px",
        background: "#16181d",
        color: "#f6f7f9",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
        <div style={{ width: 20, height: 20, borderRadius: 6, background: "#58c4dc" }} />
        <div
          style={{
            fontSize: 26,
            letterSpacing: 4,
            textTransform: "uppercase",
            color: "#6e7681",
          }}
        >
          {SITE_NAME}
        </div>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 28 }}>
        <div style={{ display: "flex", fontSize: 68, fontWeight: 700, lineHeight: 1.1 }}>
          {title}
        </div>
        {description ? (
          <div style={{ display: "flex", fontSize: 32, color: "#b0b8c4", lineHeight: 1.35 }}>
            {description}
          </div>
        ) : null}
      </div>

      <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
        <div style={{ height: 6, width: 72, borderRadius: 3, background: "#58c4dc" }} />
        <div style={{ fontSize: 26, color: "#6e7681" }}>Matemática Aplicada à Computação</div>
      </div>
    </div>,
    { ...SIZE },
  );
}
