export { mdxComponents } from "./registry";
export { Alternatives, Alternative } from "./components/alternatives";
export { Callout } from "./components/callout";
export { Collapsible } from "./components/collapsible";
export { Exercise, Answer } from "./components/exercise";
export { PixelGrid } from "./components/pixel-grid";
export { Proof } from "./components/proof";
export { Quiz, Option } from "./components/quiz";
export { RegionDiagram } from "./components/region-diagram";
export { StepByStep, Step } from "./components/step-by-step";
export { YouTube } from "./components/youtube";
